//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gcpe.ENewsletters.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class article
    {
        public int articleid { get; set; }
        public Nullable<int> editionid { get; set; }
        public string name { get; set; }
        public Nullable<int> active { get; set; }
        public string subject { get; set; }
        public Nullable<System.DateTime> aritcledate { get; set; }
        public Nullable<int> htmlcomid { get; set; }
        public Nullable<int> publishstatus { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<int> createuserid { get; set; }
        public Nullable<System.DateTime> updatedate { get; set; }
        public Nullable<int> updateuserid { get; set; }
        public string foldername { get; set; }
        public string key { get; set; }
    
        public virtual user user { get; set; }
        public virtual edition edition { get; set; }
        public virtual htmlcomponent htmlcomponent { get; set; }
        public virtual publishstatu publishstatu { get; set; }
        public virtual user user1 { get; set; }
    }
}
