//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gcpe.ENewsletters.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class boxcontent
    {
        public boxcontent()
        {
            this.boxcontent1 = new HashSet<boxcontent>();
        }
    
        public int boxcontentid { get; set; }
        public Nullable<int> editionid { get; set; }
        public Nullable<int> newsletterboxid { get; set; }
        public string title { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string picturename { get; set; }
        public string picturealttext { get; set; }
        public string hyperlink { get; set; }
        public Nullable<int> htmlcomid { get; set; }
        public string readmorelink { get; set; }
        public Nullable<int> positioncolumn { get; set; }
        public Nullable<int> positionorder { get; set; }
        public Nullable<int> masterboxcontentid { get; set; }
        public string hyperlinktarget { get; set; }
    
        public virtual edition edition { get; set; }
        public virtual htmlcomponent htmlcomponent { get; set; }
        public virtual ICollection<boxcontent> boxcontent1 { get; set; }
        public virtual boxcontent boxcontent2 { get; set; }
        public virtual newsletterbox newsletterbox { get; set; }
    }
}
