//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gcpe.ENewsletters.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class color
    {
        public color()
        {
            this.newsletterboxes = new HashSet<newsletterbox>();
        }
    
        public int colorid { get; set; }
        public Nullable<int> red { get; set; }
        public Nullable<int> green { get; set; }
        public Nullable<int> blue { get; set; }
    
        public virtual ICollection<newsletterbox> newsletterboxes { get; set; }
    }
}
