//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gcpe.ENewsletters.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class edition_history
    {
        public int ID { get; set; }
        public Nullable<int> editionid { get; set; }
        public Nullable<System.DateTime> changedate { get; set; }
        public Nullable<int> changebyuserid { get; set; }
        public string changetxt { get; set; }
    }
}
