//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gcpe.ENewsletters.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class edition
    {
        public edition()
        {
            this.articles = new HashSet<article>();
            this.boxcontents = new HashSet<boxcontent>();
        }
    
        public int editionid { get; set; }
        public Nullable<int> active { get; set; }
        public Nullable<int> newsletterid { get; set; }
        public string name { get; set; }
        public Nullable<int> folderid { get; set; }
        public string subject { get; set; }
        public Nullable<int> subscriberCount { get; set; }
        public Nullable<int> approveruserid { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<int> createuserid { get; set; }
        public Nullable<System.DateTime> updatedate { get; set; }
        public Nullable<int> updateuserid { get; set; }
        public Nullable<System.DateTime> approvedate { get; set; }
        public Nullable<int> fontsize { get; set; }
        public Nullable<int> ispublish { get; set; }
        public Nullable<int> distributedPreviously { get; set; }
        public Nullable<bool> distributeAvailable { get; set; }
        public Nullable<bool> displayPublic { get; set; }
        public Nullable<System.DateTime> originalPublishDt { get; set; }
        public Nullable<int> newslettertemplateid { get; set; }
        public Nullable<System.DateTime> originalDistributeDt { get; set; }
        public string key { get; set; }
    
        public virtual ICollection<article> articles { get; set; }
        public virtual ICollection<boxcontent> boxcontents { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
        public virtual folder folder { get; set; }
        public virtual user user2 { get; set; }
        public virtual newslettertemplate newslettertemplate { get; set; }
    }
}
