//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gcpe.ENewsletters.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class file
    {
        public int fileid { get; set; }
        public Nullable<System.Guid> guid { get; set; }
        public Nullable<int> folderid { get; set; }
        public Nullable<int> type { get; set; }
        public string name { get; set; }
        public string fname { get; set; }
        public string ftype { get; set; }
        public Nullable<int> fsize { get; set; }
        public Nullable<int> width { get; set; }
        public Nullable<int> height { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<int> createuserid { get; set; }
        public byte[] image { get; set; }
        public Nullable<bool> active { get; set; }
    
        public virtual user user { get; set; }
        public virtual folder folder { get; set; }
    }
}
