//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gcpe.ENewsletters.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class folder
    {
        public folder()
        {
            this.editions = new HashSet<edition>();
            this.files = new HashSet<file>();
            this.folder1 = new HashSet<folder>();
            this.newsletters = new HashSet<newsletter>();
            this.usergroups = new HashSet<usergroup>();
        }
    
        public int folderid { get; set; }
        public Nullable<int> parentfolderid { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<int> createuserid { get; set; }
    
        public virtual ICollection<edition> editions { get; set; }
        public virtual ICollection<file> files { get; set; }
        public virtual user user { get; set; }
        public virtual ICollection<folder> folder1 { get; set; }
        public virtual folder folder2 { get; set; }
        public virtual ICollection<newsletter> newsletters { get; set; }
        public virtual ICollection<usergroup> usergroups { get; set; }
    }
}
