//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gcpe.ENewsletters.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class htmlcomponent
    {
        public htmlcomponent()
        {
            this.articles = new HashSet<article>();
            this.boxcontents = new HashSet<boxcontent>();
            this.newslettertemplates = new HashSet<newslettertemplate>();
        }
    
        public int htmlcomid { get; set; }
        public string type { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string content { get; set; }
    
        public virtual ICollection<article> articles { get; set; }
        public virtual ICollection<boxcontent> boxcontents { get; set; }
        public virtual ICollection<newslettertemplate> newslettertemplates { get; set; }
    }
}
