//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gcpe.ENewsletters.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsletterTemplatesBox
    {
        public int newslettertemplatesboxid { get; set; }
        public Nullable<int> newsletterboxid { get; set; }
        public Nullable<int> newslettertemplateid { get; set; }
    
        public virtual newsletterbox newsletterbox { get; set; }
        public virtual newslettertemplate newslettertemplate { get; set; }
    }
}
