//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gcpe.ENewsletters.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class newsletterbox
    {
        public newsletterbox()
        {
            this.boxcontents = new HashSet<boxcontent>();
            this.NewsletterTemplatesBoxes = new HashSet<NewsletterTemplatesBox>();
        }
    
        public int newsletterboxid { get; set; }
        public string name { get; set; }
        public Nullable<int> boxtypeid { get; set; }
        public Nullable<int> transparent { get; set; }
        public Nullable<int> bgcolorid { get; set; }
        public Nullable<int> cornertypeid { get; set; }
        public bool active { get; set; }
    
        public virtual ICollection<boxcontent> boxcontents { get; set; }
        public virtual boxtype boxtype { get; set; }
        public virtual color color { get; set; }
        public virtual cornertype cornertype { get; set; }
        public virtual ICollection<NewsletterTemplatesBox> NewsletterTemplatesBoxes { get; set; }
    }
}
