//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gcpe.ENewsletters.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsletterTemplatesBannerImage
    {
        public int newslettertemplatebannerimageid { get; set; }
        public int newslettertemplateid { get; set; }
        public string coordinates { get; set; }
        public string url { get; set; }
    
        public virtual newslettertemplate newslettertemplate { get; set; }
    }
}
