//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gcpe.ENewsletters.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class newslettertemplate
    {
        public newslettertemplate()
        {
            this.editions = new HashSet<edition>();
            this.NewsletterTemplatesBannerImages = new HashSet<NewsletterTemplatesBannerImage>();
            this.NewsletterTemplatesBoxes = new HashSet<NewsletterTemplatesBox>();
            this.NewsletterTemplatesFooterImages = new HashSet<NewsletterTemplatesFooterImage>();
            this.NewsletterTemplatesFooterLinks = new HashSet<NewsletterTemplatesFooterLink>();
        }
    
        public int newslettertemplateid { get; set; }
        public int newsletterid { get; set; }
        public string version { get; set; }
        public Nullable<int> bannerfileid { get; set; }
        public string banner_coords { get; set; }
        public Nullable<int> backgroundfileid { get; set; }
        public Nullable<int> backgroundcolorid { get; set; }
        public Nullable<int> footerfileid { get; set; }
        public Nullable<int> footercolorid { get; set; }
        public string footer_coords { get; set; }
        public string footer_contact_link { get; set; }
        public string footer_area_link { get; set; }
        public Nullable<int> artfileid { get; set; }
        public Nullable<int> artcolorid { get; set; }
        public int htmlcomid { get; set; }
    
        public virtual ICollection<edition> editions { get; set; }
        public virtual htmlcomponent htmlcomponent { get; set; }
        public virtual newsletter newsletter { get; set; }
        public virtual ICollection<NewsletterTemplatesBannerImage> NewsletterTemplatesBannerImages { get; set; }
        public virtual ICollection<NewsletterTemplatesBox> NewsletterTemplatesBoxes { get; set; }
        public virtual ICollection<NewsletterTemplatesFooterImage> NewsletterTemplatesFooterImages { get; set; }
        public virtual ICollection<NewsletterTemplatesFooterLink> NewsletterTemplatesFooterLinks { get; set; }
    }
}
