//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gcpe.ENewsletters.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class publishstatu
    {
        public publishstatu()
        {
            this.articles = new HashSet<article>();
        }
    
        public int publishstatusid { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<article> articles { get; set; }
    }
}
