//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gcpe.ENewsletters.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class readcounter
    {
        public int readcounterid { get; set; }
        public Nullable<int> articleid { get; set; }
        public Nullable<int> editionid { get; set; }
        public Nullable<int> emailrecipientid { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<System.DateTime> readdate { get; set; }
    }
}
