//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gcpe.ENewsletters.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class usergroup
    {
        public usergroup()
        {
            this.newsletters = new HashSet<newsletter>();
        }
    
        public int usergroupid { get; set; }
        public Nullable<int> folderid { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string bgcolor_default { get; set; }
        public string footercolor_default { get; set; }
        public string newsletter_link { get; set; }
        public string latestedition_link { get; set; }
        public Nullable<bool> active { get; set; }
    
        public virtual folder folder { get; set; }
        public virtual ICollection<newsletter> newsletters { get; set; }
    }
}
